config/routes.rb
Projectchef::Application.routes.draw do

resources :events
resources :chef_application

devise_for :users,  path_names: {sign_in: "login", sign_out: "logout"},
                    controllers: {omniauth_callbacks: "omniauth_callbacks"}

root to: 'static_pages#home'
match '/home', to: 'static_pages#home'
match '/faq', to: 'static_pages#faq'
match '/about', to: 'static_pages#about'
match '/contact', to: 'static_pages#contact'
match '/how_it_works', to: 'static_pages#how_it_works'
match '/chef_apply', to: 'chef_application#new', :as => :new_chef_application
match '/pending_chef_applications', to: 'chef_application#show', :as => :pending_chef_application
match '/search', to: 'user#show'
match '/create_event', to: 'event#new'
end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :address_kind, :address_type, :address_type_identifier, :city_town, :country, :minor_municipality, :postal_area, :province_state_county, :street_direction, :street_number, :street_number_suffix, :street_type

  # Associations
  belongs_to :addressable, :polymorphic => true
end

app/models/appetizer.rb
class Appetizer < ActiveRecord::Base
  attr_accessible :description, :name

  # Associations
  belongs_to :users
  has_one :photos, :as => :imageable
  has_and_belongs_to_many :menus
end

app/models/chef_application.rb
class ChefApplication < ActiveRecord::Base
  attr_accessible :about_me, :city, :email, :first_name, :last_name, :motivation, :phone_number, :profile_pic

  def self.new_application(application)
    new_chef = ChefApplication.new(
                :first_name => application[:first_name],
                :last_name => application[:last_name],
                :email => application[:email],
                :city => application[:city],
                :phone_number => application[:phone_number].gsub(/[^0-9]/, "").to_i,
                :about_me => application[:about_me],
                :motivation => application[:motivation])
    new_chef.save
  end
end

app/models/dessert.rb
class Dessert < ActiveRecord::Base
  attr_accessible :description, :name

  # Associations
  belongs_to :users
  has_one :photos, :as => :imageable
  has_and_belongs_to_many :menus
end

app/models/entree.rb
class Entree < ActiveRecord::Base
  attr_accessible :description, :name

  # Associations
  belongs_to :users
  has_one :photos, :as => :imageable
  has_and_belongs_to_many :menus
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :budget, :end_time, :event_date, :num_of_appetizers, :num_of_desserts, :num_of_entrees, :number_of_guests, :occasion, :start_time

  attr_protected :event_price, :final_price

  # Associations
  belongs_to :users
  has_many :photos, :as => :imageable
  has_many :addresses, :as => :addressable
  has_many :event_menus
  has_many :menus, :through => :event_menus
end

app/models/event_menu.rb
class EventMenu < ActiveRecord::Base
  attr_accessible :selected_menu

  belongs_to :event
  belongs_to :menu
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :offered_price

  # Associations
  belongs_to :users
  has_and_belongs_to_many :appetizers
  has_and_belongs_to_many :entrees
  has_and_belongs_to_many :desserts
  has_many :event_menus
  has_many :events, :through => :event_menus
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :caption, :file_path

  # Associations
  belongs_to :imageable, :polymorphic => true
  mount_uploader :file_path, PhotosUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body

  # Validation rules
  validates_presence_of :first_name, :last_name

  # Associations
  has_many :photos, :as => :imageable
  has_many :addresses, :as => :addressable
  has_many :reviews
  has_many :events
  has_many :menus

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
  end

  def create
  end

  def show
  end

  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

  def faq
  end

  def how_it_works
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    @devise_mapping.to
  end
end

app/helpers/chef_application_helper.rb
module ChefApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container"
    <nav>
      <ul>
        <li><%= link_to "Chef Application", new_chef_application_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "FAQ", faq_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ProjectChef", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Applications", pending_chef_application_path %></li>
          <li><%= link_to "How it works", how_it_works_path %></li>
          <li><%= link_to "Create Event Posting", create_event_path %></li>
          <li><%= link_to "Our Team", about_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <button class="demo btn btn-primary btn-small" data-toggle="modal" href="#LogInModal">LOG IN / SIGN UP</button>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sign_up_login_modal.html.erb
<div id="LogInModal" class="modal hide fade" tabindex="-1" data-width="640">
  <div class="modal-body">
    <div class="row-fluid">
      <div class="span12">
        <%= render "devise/sessions/new_devise_session_form" %>
        <button class="demo btn btn-primary btn-small" data-dismiss="modal" data-toggle="modal" href="#SignUpModal">Not yet a member? Sign up</button>
      </div>
    </div>
  </div>
</div>
<div id="SignUpModal" class="modal hide fade" tabindex="-1" data-width="640">
  <div class="modal-body">
    <div class="row-fluid">
      <div class="span12">
        <%= render "devise/registrations/new_devise_registration_form" %>
        <button class="demo btn btn-primary btn-small" data-dismiss="modal" data-toggle="modal" href="#LogInModal">Already a member?</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectchef</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application", "gmaps.js" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
      <!-- google maps -->
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <%= render 'layouts/shim' %>
  </head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/sign_up_login_modal' %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/forms/_main_search_bar_form.html.erb
<div class="container-fluid">
  <div class="hero-unit">
    <h3>Find a chef for your event!</h1>
    <div class="row">
      <div class="span12">
        <%= form_tag('/search', :method => 'get', :class => 'form-horizontal') do %>
          <%= text_field_tag 'gmaps-input-address', nil, :placeholder => 'Where\'s the event happening?', :autofocus => true, :class => "input-large" %>
          <%= text_field_tag 'date', nil, :placeholder => 'Date', :class => 'datepicker input-small' %>
          <%= text_field_tag 'cuisine', nil, :placeholder => 'Cuisine',
            :class => 'input-medium' %>
          <%= submit_tag "Find Chef!", :class => 'btn btn-inverse btn-large' %>
        <% end %>
      </div>
    </div>
  </div>
</div>